version: "3.9"

services:
  backend:
    build: .
    image: cheko-app-be
    container_name: cheko-be
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cheko
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: cheko-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge