server:
  servlet:
    context-path: /api
spring:
  application:
    name: cheko-app
  config:
    import: classpath:env.properties
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

minio:
  url: http://localhost:9000
  bucket: my-bucket
  url-prefix: http://localhost:9000/my-bucket/